# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-20 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='upwd',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
    ]
